//水果
export const FRUIT_CHANGE_TYPE = 'FRUIT_CHANGE_TYPE'

export const FRUIT_LIST_GET_START = 'FRUIT_LIST_GET_START'
export const FRUIT_LIST_GET_SUCCESS = 'FRUIT_LIST_GET_SUCCESS'
export const FRUIT_LIST_GET_ERROR = 'FRUIT_LIST_GET_ERROR'

export const FRUIT_DETAIL_GET_START = 'FRUIT_DETAIL_GET_START'
export const FRUIT_DETAIL_GET_SUCCESS = 'FRUIT_DETAIL_GET_SUCCESS'
export const FRUIT_DETAIL_GET_ERROR = 'FRUIT_DETAIL_GET_ERROR'
export const FRUIT_DETAIL_CMT_LIKE = 'FRUIT_DETAIL_CMT_LIKE'
export const FRUIT_DETAIL_CMT_GET_START = 'FRUIT_DETAIL_CMT_GET_START'
export const FRUIT_DETAIL_CMT_GET_SUCCESS = 'FRUIT_DETAIL_CMT_GET_SUCCESS'
export const FRUIT_DETAIL_CMT_GET_ERROR = 'FRUIT_DETAIL_CMT_GET_ERROR'


export const CART_UPDPOS = 'CART_UPDPOS'
export const CART_ADD = 'CART_ADD'
//购物车
export const CART_EDIT = 'CART_EDIT'
export const CART_CLEAR = 'CART_CLEAR'
export const CART_CHANGE_COUPON = 'CART_CHANGE_COUPON'
export const CART_SUBMIT_START = 'CART_SUBMIT_START'
export const CART_SUBMIT_SUCCESS = 'CART_SUBMIT_SUCCESS'
export const CART_SUBMIT_ERROR = 'CART_SUBMIT_ERROR'
export const CART_CLEAR_COUPON = 'CART_CLEAR_COUPON'

//优惠券
export const COUPON_CHANGE_TYPE = 'COUPON_CHANGE_TYPE'
export const COUPON_GET_START = 'COUPON_GET_START'
export const COUPON_GET_SUCCESS = 'COUPON_GET_SUCCESS'
export const COUPON_GET_ERROR = 'COUPON_GET_ERROR'
export const COUPON_DETAIL_GET_ERROR = 'COUPON_DETAIL_GET_ERROR'
export const COUPON_DETAIL_GET_START = 'COUPON_DETAIL_GET_START'
export const COUPON_DETAIL_GET_SUCCESS = 'COUPON_DETAIL_GET_SUCCESS'

//积分
export const POINT_CHANGE_TYPE = 'POINT_CHANGE_TYPE'
export const POINT_GET_EXCH_START = 'POINT_GET_EXCH_START'
export const POINT_GET_EXCH_SUCCESS = 'POINT_GET_EXCH_SUCCESS'
export const POINT_GET_EXCH_ERROR = 'POINT_GET_EXCH_ERROR'
export const POINT_GET_REC_START = 'POINT_GET_REC_START'
export const POINT_GET_REC_SUCCESS = 'POINT_GET_REC_SUCCESS'
export const POINT_GET_REC_ERROR = 'POINT_GET_REC_ERROR'
export const POINT_GET_USE_START = 'POINT_GET_USE_START'
export const POINT_GET_USE_SUCCESS = 'POINT_GET_USE_SUCCESS'
export const POINT_GET_USE_ERROR = 'POINT_GET_USE_ERROR'
export const POINT_EXCHANGE_SUCCESS = 'POINT_EXCHANGE_SUCCESS'

//订单操作
export const ORDER_CHANGE_TYPE = 'ORDER_CHANGE_TYPE'
export const ORDER_LIST_GET_START = 'ORDER_LIST_GET_START'
export const ORDER_LIST_GET_SUCCESS = 'ORDER_LIST_GET_SUCCESS'
export const ORDER_LIST_GET_ERROR = 'ORDER_LIST_GET_ERROR'
export const ORDER_DETAIL_GET_START = 'ORDER_DETAIL_GET_START'
export const ORDER_DETAIL_GET_SUCCESS = 'ORDER_DETAIL_GET_SUCCESS'
export const ORDER_DETAIL_GET_ERROR = 'ORDER_DETAIL_GET_ERROR'
export const ORDER_FINISH = 'ORDER_FINISH'
export const ORDER_CHANGE_STATE = 'ORDER_CHANGE_STATE'

//城市选择
export const CITY_CHANGE_TYPE = 'CITY_CHANGE_TYPE'
export const CITY_CHANGE_QU = 'CITY_CHANGE_QU'
export const CITY_CHANGE_CITY = 'CITY_CHANGE_CITY'
export const CITY_GET_START = 'CITY_GET_START'
export const CITY_GET_SUCCESS = 'CITY_GET_SUCCESS'
export const CITY_GET_ERROR = 'CITY_GET_ERROR'


//收货地址
export const ADDR_SET_DEF = 'ADDR_SET_DEF'
export const ADDR_CLEAR = 'ADDR_CLEAR'
export const ADDR_ADD_START = 'ADDR_ADD_START'
export const ADDR_ADD_SAVE = 'ADDR_ADD_SAVE'
export const ADDR_ADD_ERROR = 'ADDR_ADD_ERROR'
export const ADDR_EDIT = 'ADDR_EDIT'
export const ADDR_DEL_START = 'ADDR_DEL_START'
export const ADDR_DEL = 'ADDR_DEL'
export const ADDR_DEL_ERROR = 'ADDR_DEL_ERROR'
export const ADDR_UPD = 'ADDR_UPD'
export const ADDR_CHOOSE = 'ADDR_CHOOSE'
export const ADDR_CHOOSE_TIME = 'ADDR_CHOOSE_TIME'
export const ADDR_LIST_GET_START = 'ADDR_LIST_GET_START'
export const ADDR_LIST_GET_SUCCESS = 'ADDR_LIST_GET_SUCCESS'
export const ADDR_LIST_GET_ERROR = 'ADDR_LIST_GET_ERROR'
export const ADDR_UPDATE_START = 'ADDR_UPDATE_START'
export const ADDR_UPDATE_SUCCESS = 'ADDR_UPDATE_SUCCESS'
export const ADDR_UPDATE_ERROR = 'ADDR_UPDATE_ERROR'

/*detail*/
export const DETAIL_LIKE = 'DETAIL_LIKE'
export const DETAIL_UNLIKE = 'DETAIL_UNLIKE'

//用户
export const USER_GET_START = 'USER_GET_START'
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS'
export const USER_GET_ERROR = 'USER_GET_ERROR'