export const CART_UPDPOS = 'CART_UPDPOS'
export const CART_EDIT = 'CART_EDIT'

export const COUPON_CHANGE_TYPE = 'COUPON_CHANGE_TYPE'


export const POINT_CHANGE_TYPE = 'POINT_CHANGE_TYPE'


export const ORDER_CHANGE_TYPE = 'ORDER_CHANGE_TYPE'


export const CITY_CHANGE_TYPE = 'CITY_CHANGE_TYPE'
export const CITY_CHANGE_QU = 'CITY_CHANGE_QU'
export const CITY_CHANGE_CITY = 'CITY_CHANGE_CITY'